#!/bin/bash
# post-receive

#################### ORIENTATION ####################

ENVIRONMENT="development"
WEBUSER=$(apachectl -S | egrep '(User: name)' | grep -o -P '(?<=name=").*(?=" id)')
WEBGROUP=$(apachectl -S | egrep '(Group: name)' | grep -o -P '(?<=name=").*(?=" id)')

USERHOME="$(eval echo ~"$WEBUSER")"
DEPLOY="${USERHOME}/"

#################### PROTECT THE SERVER ####################

if [[ -z "${WEBUSER}" ]]; then
  echo "The web user could not be detected."
  exit 1
fi

if [[ -z "${WEBGROUP}" ]]; then
  echo "The web group could not be detected."
  exit 1
fi

if [[ -z "${USERHOME}" ]]; then
  echo "The web user home directory could not be detected."
  exit 1
fi

if [[ $USERHOME == "/root" ]]; then
  echo "The web user home directory is /root. This may be an error!"
  exit 1
fi

if [[ $USERHOME == "/" ]]; then
  echo "Cannot deploy to system root directory!"
  exit 1
fi

# Get environment
source $USERHOME/config/.env

if [[ -z "${APP_ROOT}" ]]; then
  echo "The application root is unset. Check the /config/.env file."
  exit 1
fi

#################### DEPLOY ####################

read oldrev newrev refname

BRANCH=${refname#refs/heads/}

if [[ $BRANCH != 'master' ]]; then
  echo "Received branch $BRANCH, not deploying."
  exit 1
fi

# edit deploy path
GIT_WORK_TREE=$DEPLOY git checkout -f master > /dev/null 2>&1

cd $APP_ROOT

# Ensure directory permissions remain correct (644 for files; 755 for directories)
find . -type f -exec chmod 644 -- {} +
find . -type d -exec chmod 755 {} +

# Make sure the web user owns the entire web directory
chown -R $WEBUSER:$WEBGROUP $APP_ROOT

composer update
vendor/bin/phinx migrate -e $ENVIRONMENT

echo "DEPLOY: master(#{to}) copied to /var/www"
echo "Don't forget to run any seeds you may need"
